/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sgt.UI;
import sgt.session.UserSession;
import sgt.util.DatabaseHelper;
import sgt.util.WindowHelper;
/**
 *
 * @author Cii
 */
public class AddFacultyUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddFacultyUI.class.getName());

    /**
     * Creates new form AddFacultyUI
     */
    public AddFacultyUI() {
        initComponents();
        populate_table();
    }
    
     private void populate_table() {
        String sql = "SELECT full_name, username, password FROM tbl_faculty";
        sgt.util.TableHelper.updateTable(tbl_faculty, sql, "");
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddFaculty = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        usrnme = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        full_Name1 = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        Pass = new javax.swing.JLabel();
        AddFac = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_faculty = new javax.swing.JTable();
        back = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        AddFac1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddFaculty.setBackground(new java.awt.Color(255, 153, 51));
        AddFaculty.setBorder(javax.swing.BorderFactory.createTitledBorder("Faculty Information"));

        Name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Name.setText("Full Name:");

        usrnme.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usrnme.setText("Username");

        username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username.addActionListener(this::usernameActionPerformed);

        full_Name1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        full_Name1.addActionListener(this::full_Name1ActionPerformed);

        password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password.addActionListener(this::passwordActionPerformed);

        Pass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pass.setText("Password:");

        AddFac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddFac.setText("Add Faculty");
        AddFac.addActionListener(this::AddFacActionPerformed);

        tbl_faculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Full Name", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(tbl_faculty);

        back.setText("back");
        back.addActionListener(this::backActionPerformed);

        Update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(this::UpdateActionPerformed);

        AddFac1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddFac1.setText("Clear");
        AddFac1.addActionListener(this::AddFac1ActionPerformed);

        javax.swing.GroupLayout AddFacultyLayout = new javax.swing.GroupLayout(AddFaculty);
        AddFaculty.setLayout(AddFacultyLayout);
        AddFacultyLayout.setHorizontalGroup(
            AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddFacultyLayout.createSequentialGroup()
                .addGroup(AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddFacultyLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddFacultyLayout.createSequentialGroup()
                                .addGroup(AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usrnme)
                                    .addComponent(Name))
                                .addGap(28, 28, 28)
                                .addGroup(AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(full_Name1)
                                    .addComponent(username)))
                            .addGroup(AddFacultyLayout.createSequentialGroup()
                                .addComponent(Pass)
                                .addGap(32, 32, 32)
                                .addComponent(password))))
                    .addGroup(AddFacultyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)
                        .addGap(0, 215, Short.MAX_VALUE))
                    .addGroup(AddFacultyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddFacultyLayout.createSequentialGroup()
                                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addComponent(AddFac, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddFacultyLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(AddFac1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AddFacultyLayout.setVerticalGroup(
            AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddFacultyLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(full_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrnme)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pass)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFac)
                    .addComponent(Update))
                .addGap(18, 18, 18)
                .addComponent(AddFac1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(24, 24, 24))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void full_Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_full_Name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_full_Name1ActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void AddFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFacActionPerformed
        String fullName = full_Name1.getText().trim();
        String uname = username.getText().trim();
        String pword = password.getText().trim();
        
        if (fullName.isEmpty() || uname.isEmpty() || pword.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        String sql = "INSERT INTO tbl_faculty (full_name, username, password) VALUES(?, ?, ?)";
        boolean success = DatabaseHelper.executeUpdate(sql, fullName, uname, pword);


        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Faculty added successfully!");
            full_Name1.setText("");
            username.setText("");
            password.setText("");
            populate_table();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to add faculty!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    public static void main(String args[]) {
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new AddFacultyUI().setVisible(true));
    }//GEN-LAST:event_AddFacActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        String role = sgt.session.UserSession.getCurrentRole();
        if ("faculty".equals(role)) {
            WindowHelper.openWindow(this, new DashboardFaculty(UserSession.getCurrentUser()));
        } else {
            WindowHelper.openWindow(this, new DashboardAdmin(UserSession.getCurrentUser()));
        } // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        int row = tbl_faculty.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a faculty from the table first!");
        return;
    }

    String fullName = full_Name1.getText().trim();
    String uname = username.getText().trim();
    String pword = password.getText().trim();
    String facultyId = tbl_faculty.getValueAt(row, 0).toString(); // assuming first column is ID

    if (fullName.isEmpty() || uname.isEmpty() || pword.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fields cannot be empty!");
        return;
    }

    String sql = "UPDATE tbl_faculty SET full_name = ?, username = ?, password = ? WHERE faculty_id = ?";
    boolean success = DatabaseHelper.executeUpdate(sql, fullName, uname, pword, facultyId);

    if (success) {
        javax.swing.JOptionPane.showMessageDialog(this, "Faculty updated successfully!");
        populate_table();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Update failed.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }// TODO add your handling code here:
    }//GEN-LAST:event_UpdateActionPerformed

    private void AddFac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFac1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddFac1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFac;
    private javax.swing.JButton AddFac1;
    private javax.swing.JPanel AddFaculty;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Pass;
    private javax.swing.JButton Update;
    private javax.swing.JButton back;
    private javax.swing.JTextField full_Name1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField password;
    private javax.swing.JTable tbl_faculty;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usrnme;
    // End of variables declaration//GEN-END:variables
}
