/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sgt.UI;
import java.awt.Color;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import sgt.util.TableHelper;
import javax.swing.JOptionPane;
/**
 *
 * @author Cii
 */
public class AddstudUI extends javax.swing.JFrame {
    
    
    
    private final String BASE_STUDENT_QUERY = 
        "SELECT s.student_number as 'Student No.', " +
        "s.first_name as 'First Name', " +
        "s.last_name as 'Last Name', " +
        "s.year_level as 'Year', " +
        "p.program_code as 'Program', " + 
        "s.faculty_id as 'Faculty ID', " +
        "s.admin_id as 'Admin ID' " +
        "FROM tbl_students s " +
        "JOIN tbl_programs p ON s.program_id = p.program_id";
    
    public AddstudUI(){
        initComponents();
        setResizable(false);
        jPanel1.setBackground(Color.decode("#F28C5E"));
        populate_table();
        loadProgramDrodown();
    }
    
    private void loadProgramDrodown(){
        program.removeAllItems();
        program.addItem("Select Program");

        for (String p : sgt.service.StudentService.getProgramList()){
            program.addItem(p);
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddstudUI.class.getName());

    /**
     * Creates new form AddstudUI
     */
    
    private void populate_table(){
        TableHelper.updateTable(tbl_students, BASE_STUDENT_QUERY, "");
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        yrlevel = new javax.swing.JComboBox<>();
        program = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_students = new javax.swing.JTable();
        backb = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Student Information"));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("First Name:");

        fname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fname.addActionListener(this::fnameActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Last Name:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Year Level:");

        lname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lname.addActionListener(this::lnameActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Program:");

        jButton1.setFont(new java.awt.Font("Public Sans Medium", 1, 12)); // NOI18N
        jButton1.setText("Add Student");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        yrlevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Year", "2nd Year", "3rd Year", "4th Year" }));
        yrlevel.addActionListener(this::yrlevelActionPerformed);

        program.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Information Technology", "Entertainment and Multimedia Computing" }));
        program.addActionListener(this::programActionPerformed);

        tbl_students.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Year Level", "Program"
            }
        ));
        tbl_students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_studentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_students);

        backb.setText("back");
        backb.addActionListener(this::backbActionPerformed);

        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Public Sans Medium", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search Student No.");

        jToggleButton1.setText("Delete");
        jToggleButton1.addActionListener(this::jToggleButton1ActionPerformed);

        jButton2.setFont(new java.awt.Font("Public Sans Medium", 1, 12)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backb))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(yrlevel, 0, 150, Short.MAX_VALUE)
                                    .addComponent(fname)
                                    .addComponent(program, 0, 1, Short.MAX_VALUE)
                                    .addComponent(lname)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yrlevel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(program, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backb)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("Faculty Information");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String firstName = fname.getText().trim();
        String lastName = lname.getText().trim();
        int yearValue = yrlevel.getSelectedIndex() + 1;
        String studentNum = sgt.service.StudentService.generateNextID();
        
        String selectedProgram = program.getSelectedItem().toString();
        int programId = sgt.service.StudentService.getProgramId(selectedProgram);
           
        int currentId = sgt.session.UserSession.getUserId();
        String role = sgt.session.UserSession.getCurrentRole();
        
        Integer fId = null; //facultyId
        Integer aId = null; //adminId
        
        if("faculty".equals(role)){
            fId = currentId;
        } else {
            aId = currentId;
        }
        
        if (firstName.isEmpty() || lastName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }

        sgt.model.Student newStudent = new sgt.model.Student(studentNum, firstName, lastName, yearValue, programId, fId, aId);
        sgt.dao.studentManagementDAO dao = new sgt.dao.studentManagementDAO();
        boolean success = dao.addStudent(newStudent);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Student added successfully!");
            fname.setText("");
            lname.setText("");
            populate_table(); // Refresh the table
        } else {
            JOptionPane.showMessageDialog(this, "Failed to save to database.");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void yrlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yrlevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yrlevelActionPerformed

    private void programActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_programActionPerformed

    private void backbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbActionPerformed
        String role = sgt.session.UserSession.getCurrentRole();
        if ("faculty".equals(role)) {
            new DashboardFaculty(sgt.session.UserSession.getCurrentUser()).setVisible(true);
        } else {
            new DashboardAdmin(sgt.session.UserSession.getCurrentUser()).setVisible(true);
        }
    this.dispose();   
    }//GEN-LAST:event_backbActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String searchID = jTextField1.getText().trim();
        if(searchID.isEmpty()){
            populate_table();
        } else {
            String sql = BASE_STUDENT_QUERY + " WHERE s.student_number LIKE ?";
            sgt.util.TableHelper.updateTable(tbl_students, sql,  "%" + searchID + "%");
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void tbl_studentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_studentsMouseClicked
        int row = tbl_students.getSelectedRow();
        
        if(row != 1){
            fname.setText(tbl_students.getValueAt(row, 1).toString());
            lname.setText(tbl_students.getValueAt(row, 2).toString());
            
            String year = tbl_students.getValueAt(row, 3).toString();
            yrlevel.setSelectedItem(year);
            
            String programName = tbl_students.getValueAt(row, 4).toString();
            program.setSelectedItem(programName);
        }
    }//GEN-LAST:event_tbl_studentsMouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int row = tbl_students.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a student from the table first.");
            return;
        }
        
        String studentId = tbl_students.getValueAt(row, 0).toString();
        int confirm = JOptionPane.showConfirmDialog(this, "Delete student " + studentId + "?", "Confirm", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            sgt.dao.studentManagementDAO dao = new sgt.dao.studentManagementDAO();
            if (dao.deleteStudent(studentId)) {
                JOptionPane.showMessageDialog(this, "Deleted successfully.");
                populate_table();
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = tbl_students.getSelectedRow();
        if (row == -1) { 
            JOptionPane.showMessageDialog(this, "Please select a student from the table first!");
            return;
        }
        String firstName = fname.getText().trim();
        String lastName = lname.getText().trim();
        int yearValue = yrlevel.getSelectedIndex() + 1;
        String selectedProgram = program.getSelectedItem().toString();
        int programId = sgt.service.StudentService.getProgramId(selectedProgram);
        String studentNum = tbl_students.getValueAt(row, 0).toString();
        
        int currentId = sgt.session.UserSession.getUserId();
        String role = sgt.session.UserSession.getCurrentRole();
        Integer fId = "faculty".equals(role) ? currentId : null;
        Integer aId = "admin".equals(role) ? currentId : null;
        
        if (firstName.isEmpty() || lastName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fields cannot be empty!");
            return;
        }
        
        sgt.model.Student updatedStudent = new sgt.model.Student(studentNum, firstName, lastName, yearValue, programId, fId, aId);
        sgt.dao.studentManagementDAO dao = new sgt.dao.studentManagementDAO();
        
        if (dao.updateStudent(updatedStudent)) {
            JOptionPane.showMessageDialog(this, "Student updated successfully!");
            populate_table();
            sgt.util.UIHelper.clearComponents(fname, lname, yrlevel, program, tbl_students);
        } else {
            JOptionPane.showMessageDialog(this, "Update failed.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatMacLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddstudUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backb;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField lname;
    private javax.swing.JComboBox<String> program;
    private javax.swing.JTable tbl_students;
    private javax.swing.JComboBox<String> yrlevel;
    // End of variables declaration//GEN-END:variables
}
