/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sgt.UI;

import javax.swing.JOptionPane;
import sgt.session.UserSession;
import sgt.util.WindowHelper;

/**
 *
 * @author Andrew
 * @author Cii
 */
public class DashboardAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardAdmin.class.getName());

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin(String facultyName) {
        initComponents();
        String name = UserSession.getCurrentUser();
        AdminName.setText(name);
        displayStudentCount();
        }
    
    private void displayStudentCount() {
        try {
            sgt.dao.studentManagementDAO dao = new sgt.dao.studentManagementDAO();
            int count = dao.getTotalStudentCount();
            
            EnrolledStudents.setText("Total Enrolled Students: " + count);
        
        } catch (Exception e) {
            EnrolledStudents.setText("Count: Error");
            e.printStackTrace();
        }
    }
    /**
     * This method is called from withiSn the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AdminName = new javax.swing.JLabel();
        Q1 = new javax.swing.JLabel();
        StudentManagement = new javax.swing.JButton();
        SubjectManagement = new javax.swing.JButton();
        ProgramManagement = new javax.swing.JButton();
        GradesManagement = new javax.swing.JButton();
        StudentGradeSummary = new javax.swing.JButton();
        FacultyManagement = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        EnrolledStudents = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1267, 360));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setForeground(new java.awt.Color(255, 102, 0));
        jPanel2.setToolTipText("");

        jLabel2.setBackground(new java.awt.Color(255, 51, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("Admin Dashboard | Welcome,");

        AdminName.setBackground(new java.awt.Color(255, 51, 255));
        AdminName.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        AdminName.setText("Admin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(AdminName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Q1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Q1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q1.setText("What would you like to do today?");

        StudentManagement.setBackground(new java.awt.Color(255, 153, 51));
        StudentManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        StudentManagement.setForeground(new java.awt.Color(255, 255, 255));
        StudentManagement.setText("Student Management");
        StudentManagement.setPreferredSize(new java.awt.Dimension(185, 48));
        StudentManagement.addActionListener(this::StudentManagementActionPerformed);

        SubjectManagement.setBackground(new java.awt.Color(255, 153, 51));
        SubjectManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SubjectManagement.setForeground(new java.awt.Color(255, 255, 255));
        SubjectManagement.setText("Subject Management");
        SubjectManagement.setPreferredSize(new java.awt.Dimension(185, 48));
        SubjectManagement.addActionListener(this::SubjectManagementActionPerformed);

        ProgramManagement.setBackground(new java.awt.Color(255, 153, 51));
        ProgramManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProgramManagement.setForeground(new java.awt.Color(255, 255, 255));
        ProgramManagement.setText("Program Management");
        ProgramManagement.setPreferredSize(new java.awt.Dimension(185, 48));
        ProgramManagement.addActionListener(this::ProgramManagementActionPerformed);

        GradesManagement.setBackground(new java.awt.Color(255, 153, 51));
        GradesManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GradesManagement.setForeground(new java.awt.Color(255, 255, 255));
        GradesManagement.setText("Grades Management");
        GradesManagement.setPreferredSize(new java.awt.Dimension(185, 48));
        GradesManagement.addActionListener(this::GradesManagementActionPerformed);

        StudentGradeSummary.setBackground(new java.awt.Color(255, 153, 51));
        StudentGradeSummary.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        StudentGradeSummary.setForeground(new java.awt.Color(255, 255, 255));
        StudentGradeSummary.setText("Student Grade Summary");
        StudentGradeSummary.setPreferredSize(new java.awt.Dimension(185, 48));
        StudentGradeSummary.addActionListener(this::StudentGradeSummaryActionPerformed);

        FacultyManagement.setBackground(new java.awt.Color(255, 153, 51));
        FacultyManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FacultyManagement.setForeground(new java.awt.Color(255, 255, 255));
        FacultyManagement.setText("Faculty Management");
        FacultyManagement.setPreferredSize(new java.awt.Dimension(185, 48));
        FacultyManagement.addActionListener(this::FacultyManagementActionPerformed);

        jButton6.setFont(new java.awt.Font("Public Sans Medium", 0, 12)); // NOI18N
        jButton6.setText("Logout");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        EnrolledStudents.setBackground(new java.awt.Color(255, 153, 51));
        EnrolledStudents.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EnrolledStudents.setForeground(new java.awt.Color(255, 255, 255));
        EnrolledStudents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EnrolledStudents.setText("Sheesh");
        EnrolledStudents.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubjectManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProgramManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(StudentGradeSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GradesManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FacultyManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(119, 119, 119)
                        .addComponent(EnrolledStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Q1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(552, 552, 552))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FacultyManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnrolledStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GradesManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubjectManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentGradeSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProgramManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentManagementActionPerformed
        WindowHelper.openWindow(this, new AddstudUI());// TODO add your handling code here:
    }//GEN-LAST:event_StudentManagementActionPerformed

    private void SubjectManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectManagementActionPerformed
        WindowHelper.openWindow(this, new SubjectManagement());// TODO add your handling code here:
    }//GEN-LAST:event_SubjectManagementActionPerformed

    private void ProgramManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramManagementActionPerformed
        WindowHelper.openWindow(this, new ProgramManagement());// TODO add your handling code here:
    }//GEN-LAST:event_ProgramManagementActionPerformed

    private void GradesManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradesManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradesManagementActionPerformed

    private void StudentGradeSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentGradeSummaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentGradeSummaryActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int response = JOptionPane.showConfirmDialog(this,
            "Do you want to logout?",
            "Confirm",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
            WindowHelper.openWindow(this, new LoginUI());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void FacultyManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultyManagementActionPerformed
        WindowHelper.openWindow(this, new AddFacultyUI());;// TODO add your handling code here:
    }//GEN-LAST:event_FacultyManagementActionPerformed

    /**
     * @param args the command line arguments
     */
    static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardAdmin(UserSession.getCurrentUser()).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminName;
    private javax.swing.JLabel EnrolledStudents;
    private javax.swing.JButton FacultyManagement;
    private javax.swing.JButton GradesManagement;
    private javax.swing.JButton ProgramManagement;
    private javax.swing.JLabel Q1;
    private javax.swing.JButton StudentGradeSummary;
    private javax.swing.JButton StudentManagement;
    private javax.swing.JButton SubjectManagement;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
